FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /workspace

COPY DevOps/requirements.txt .

RUN python -m pip install --upgrade pip \
    && pip install -r requirements.txt

COPY DevOps/ .
COPY scripts/ /scripts/

CMD ["pytest", "tests/", "-v"]
